package ui.extra;

import model.POSController;
import java.awt.*;
import java.awt.event.FocusEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.event.*;
import javax.swing.table.DefaultTableModel;
import model.POSFactory;
import model.dto.*;
import org.jfree.chart.*;
import org.jfree.chart.plot.*;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.statistics.HistogramDataset;
import raven.glasspanepopup.GlassPanePopup;
import ui.DashboardUI;

public final class HomeUI extends javax.swing.JFrame {

    private POSController controller;
    private FocusEvent evt;

    public HomeUI(POSController controller) {
        this.controller = controller;
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Set the JFrame to full size
        setResizable(false); // Make the JFrame non-resizable
        mainPanel.removeAll();
        mainPanel.add(new KPI_UI(this.controller), BorderLayout.CENTER);
        ContributeToggleButtonFocusGained(this.evt);
        mainPanel.validate();
        
        GlassPanePopup.install(this);
        this.setMinimumSize(this.getSize());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        BackLableBtn = new javax.swing.JLabel();
        HeaderTitle = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ContributeToggleButton = new javax.swing.JToggleButton();
        SettingToggleButton = new javax.swing.JToggleButton();
        histogramPanel = new javax.swing.JPanel();
        panelBarChart = new javax.swing.JPanel();
        barChartPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BackLableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back-angle-arrow.png"))); // NOI18N
        BackLableBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackLableBtnMouseClicked(evt);
            }
        });

        HeaderTitle.setBackground(new java.awt.Color(255, 255, 255));
        HeaderTitle.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        HeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        HeaderTitle.setText("Information");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(BackLableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HeaderTitle)
                .addGap(0, 1131, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackLableBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HeaderTitle)
                .addContainerGap())
        );

        sidebarPanel.setBackground(new java.awt.Color(51, 51, 51));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 720));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        ContributeToggleButton.setBackground(new java.awt.Color(0, 0, 0));
        ContributeToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        ContributeToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/account_24px.png"))); // NOI18N
        ContributeToggleButton.setText("KPI");
        ContributeToggleButton.setBorder(null);
        ContributeToggleButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContributeToggleButtonFocusGained(evt);
            }
        });
        ContributeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContributeToggleButtonActionPerformed(evt);
            }
        });

        SettingToggleButton.setBackground(new java.awt.Color(0, 0, 0));
        SettingToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        SettingToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings-icon.png"))); // NOI18N
        SettingToggleButton.setText("Setting");
        SettingToggleButton.setBorder(null);
        SettingToggleButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SettingToggleButtonFocusGained(evt);
            }
        });
        SettingToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContributeToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(SettingToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContributeToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(SettingToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(453, 453, 453))
        );

        histogramPanel.setBackground(new java.awt.Color(0, 102, 102));
        histogramPanel.setForeground(new java.awt.Color(0, 102, 102));
        histogramPanel.setOpaque(false);
        histogramPanel.setLayout(new java.awt.BorderLayout());

        panelBarChart.setBackground(new java.awt.Color(102, 102, 102));
        panelBarChart.setLayout(new java.awt.BorderLayout());

        barChartPanel.setForeground(new java.awt.Color(0, 153, 153));
        barChartPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 666, Short.MAX_VALUE)
                        .addComponent(barChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 711, Short.MAX_VALUE)
                        .addComponent(panelBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(histogramPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(722, 722, 722))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelBarChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(histogramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                        .addGap(93, 93, 93)
                        .addComponent(barChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContributeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContributeToggleButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new KPI_UI(this.controller),BorderLayout.CENTER);
        mainPanel.validate();
    }//GEN-LAST:event_ContributeToggleButtonActionPerformed

    private void SettingToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingToggleButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new UserUI(this.controller), BorderLayout.CENTER);
        mainPanel.validate();
    }//GEN-LAST:event_SettingToggleButtonActionPerformed

    private void SettingToggleButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SettingToggleButtonFocusGained
        // TODO add your handling code here:
        allBtnFocusLost();
        SettingToggleButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_SettingToggleButtonFocusGained

    private void ContributeToggleButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContributeToggleButtonFocusGained
        // TODO add your handling code here:
        allBtnFocusLost();
        ContributeToggleButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_ContributeToggleButtonFocusGained

    private void BackLableBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackLableBtnMouseClicked
        // TODO add your handling code here:
        JFrame dashboard = new DashboardUI(this.controller);
        dashboard.setVisible(true);
        POSController.objApplicationSession.setCurrentScreen(dashboard);
        this.dispose();
    }//GEN-LAST:event_BackLableBtnMouseClicked
    
    private void allBtnFocusLost(){
        ContributeToggleButton.setBackground(new Color(255, 0, 51));        
        SettingToggleButton.setBackground(new Color(255, 0, 51));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackLableBtn;
    private javax.swing.JToggleButton ContributeToggleButton;
    private javax.swing.JLabel HeaderTitle;
    private javax.swing.JToggleButton SettingToggleButton;
    private javax.swing.JPanel barChartPanel;
    private javax.swing.JPanel histogramPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelBarChart;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
