package ui;

import model.POSController;
import javax.swing.JFrame;
import model.POSFactory;
import model.dto.Message;
import model.dto.MessageType;
import model.dto.Response;
import model.dto.UserDTO;
import raven.glasspanepopup.GlassPanePopup;
import ui.components.CommonHandler;

public class LoginUI extends javax.swing.JFrame {
    private POSController controller;
    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
    this.controller=POSFactory.getInstanceOfPOSController();
        initComponents();
        this.setLocationRelativeTo(null);
        GlassPanePopup.install(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelMain = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        passwdText = new javax.swing.JLabel();
        userText = new javax.swing.JLabel();
        loginBTN = new ui.components.Button();
        PanelTitle = new javax.swing.JPanel();
        TitleText = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Point of Sale System V 0.1 by CodeCrood");

        jPanel1.setLayout(new java.awt.BorderLayout());

        usernameField.setForeground(new java.awt.Color(255, 0, 51));
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldKeyPressed(evt);
            }
        });

        passwordField.setForeground(new java.awt.Color(255, 0, 51));
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        passwdText.setForeground(new java.awt.Color(255, 0, 51));
        passwdText.setText("Password");

        userText.setForeground(new java.awt.Color(255, 0, 51));
        userText.setText("Username");

        loginBTN.setBackground(new java.awt.Color(255, 204, 102));
        loginBTN.setForeground(new java.awt.Color(255, 255, 255));
        loginBTN.setText("Login");
        loginBTN.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(passwdText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(passwordField))
                .addGap(69, 69, 69))
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userText))
                .addGap(18, 18, 18)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwdText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(PanelMain, java.awt.BorderLayout.CENTER);

        PanelTitle.setBackground(new java.awt.Color(255, 51, 51));
        PanelTitle.setForeground(new java.awt.Color(255, 255, 255));
        PanelTitle.setToolTipText("");

        TitleText.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        TitleText.setForeground(new java.awt.Color(255, 255, 255));
        TitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleText.setText("POS");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo-Hoc-Vien-Ky-Thuat-Mat-Ma-AC.png"))); // NOI18N

        javax.swing.GroupLayout PanelTitleLayout = new javax.swing.GroupLayout(PanelTitle);
        PanelTitle.setLayout(PanelTitleLayout);
        PanelTitleLayout.setHorizontalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon)
                .addGap(27, 27, 27)
                .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        PanelTitleLayout.setVerticalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelTitleLayout.createSequentialGroup()
                        .addComponent(icon)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(PanelTitle, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        UserDTO user = new UserDTO();
        user.setUsername(usernameField.getText());
        user.setPassword(new String(passwordField.getPassword()));

        Response responseObj = POSFactory.getInstanceOfResponse();
        this.controller.verifyUser(user, responseObj);
        
        if(responseObj.isSuccessfull()){
            JFrame dashboard=new Dashboard(this.controller);
            dashboard.setVisible(true);
            POSController.objApplicationSession.setCurrentScreen(dashboard);
            this.dispose();
        }else{
            passwordField.setText("");
            GlassPanePopup.showPopup(new MessageUI(responseObj.getErrorMessages(),MessageType.Error));
        
        }
    }//GEN-LAST:event_loginBTNActionPerformed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            if (!usernameField.getText().isEmpty() && passwordField.getPassword().length > 0){
                loginBTNActionPerformed(null);
            }
            else{
                passwordField.setText("");
                Response res = new Response();
                res.messagesList.add(new Message("Please enter both username and password.",MessageType.Error));
                CommonHandler.handleResponse(res);
            }
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            if (!usernameField.getText().isEmpty() && passwordField.getPassword().length > 0){
                loginBTNActionPerformed(null);
            }
            else{
                passwordField.setText("");
                Response res = new Response();
                res.messagesList.add(new Message("Please enter both username and password.",MessageType.Error));
                CommonHandler.handleResponse(res);
            }
        }
    }//GEN-LAST:event_usernameFieldKeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelTitle;
    private javax.swing.JLabel TitleText;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private ui.components.Button loginBTN;
    private javax.swing.JLabel passwdText;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel userText;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
